version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: circleci/node:erbium-browsers # v12
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
         command: |
            git config --global user.email "xiangzhe0812@gmail.com"
            git config --global user.name "xiangzhe0812"
            yarn deploy
            
workflows:
  build:
    jobs:
      - build:
         filters:
            branches:
              ignore: gh-pages
              only: main
