version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    docker:
      - image: circleci/node:erbium-browsers # v12
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: yarn deploy
  deploy-gh-pages:
    docker:
      - image: circleci/node:erbium-browsers # v12
    steps:
      - run:
          name: Deploy to gh-pages branch
          command: NODE_DEBUG=gh-pages npx gh-pages --dotfiles --message "[skip ci] Deploy" -d dist/*
workflows:
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore: gh-pages
      - deploy-gh-pages:
          filters:
            branches:
              only: main
            requires:
              - build-and-test
