version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: circleci/node:erbium-browsers # v12
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: yarn deploy
  deploy:
    docker:
      - image: circleci/node:erbium-browsers # v12
    steps:
      - run:
          name: git 1
          command: git config --global user.email "xiangzhe0812@gmail.com"
      - run:
          name: git 2
          command: git config --global user.name "ci-build"
      - run:
          name: Deploy to gh-pages branch
          command: NODE_DEBUG=gh-pages npx gh-pages --dotfiles --message "[skip ci] Deploy" -d dist/*
workflows:
  build:
    jobs:
      - build:
         filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: mai
          
