version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:erbium-browsers # v12
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: yarn lint
  deploy-gh-pages:
    machine:
      enabled: true
    steps:
      - run: yarn deploy
workflows:
  build-and-test:
    jobs:
      - deploy-gh-pages:
        filters:
          branches:
            only: development
          requires:
            - build-and-test
